### ISSUE TITLE
Craftable custom item.

### ISSUE THREAD

**Issue by dankwow** [LepkoQQ/EasyCrafting#11]
I didn't know where to post this to get noticed.

EasyCrafting is able to create custom items from this mod:
http://www.minecraftforum.net/topic/1444108-145144forge-craft-and-enchant-v26-better-enchanting-extended-repair-system/

**Comment by LepkoQQ** [comment]
Sorry, I'm not very familiar with this mod? What is the problem? Are there recipes that are not supposed to be craftable?

**Comment by LepkoQQ** [comment]
If this is still a problem please submit a new issue with more info. Closing.
