### ISSUE TITLE
FTB + EasyCrafting renders unable to join a LAN-Server

### ISSUE THREAD

**Issue by thatsIch** [LepkoQQ/EasyCrafting#12]
Running Feed the Beast + EasyCrafting without problems.
Had no issue on SSP but when I tried to join a local Server on Hamachi it doesnt connect anymore
but with Feed the Beast alone it does.

I posted this also on the MCForum Thread but there was no response.
Since the changelog said you just updated to 1.4.5 in the latest version I assumed this bug(?) wasnt fixed in the 1.4.2 version (since FTB is running on 1.4.2)

Seems it was fixed in the update

**Comment by LepkoQQ** [comment]
Sorry that there was no response. I was taking a break for a while and might have missed it. Glad to hear I was fixed.

**Comment by thatsIch** [comment]
its k =) everybody has earned free time. Word of notice would just be great next time ;-)
