### ISSUE TITLE
Crash with latest Extra Bees Plugin

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [LepkoQQ/EasyCrafting#18]
With the Extra Bees Plugin 1.6 pre6, this crash happens: https://privatepaste.com/cd846aa13d

**Comment by agaricusb** [comment]
> java.lang.NullPointerException    at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:268)    at net.lepko.easycrafting.easyobjects.EasyItemStack.fromItemStack(EasyItemStack.java:72)

Same crash with Dartcraft: https://gist.github.com/agaricusb/5564802

This occurs due to this recent Forge change to delegate item damage: https://github.com/MinecraftForge/MinecraftForge/commit/b56d05ef9d6be5f3413cb62f2940f5b9cf3a8549

**Comment by LepkoQQ** [comment]
Can't reproduce with Extra Bees pre7.

Please test with Minecraft 1.5.2 and EasyCrafting 1.1.5 if this is still an issue.

**Comment by LepkoQQ** [comment]
closing for now, reopen the issue is present for the upcoming 1.7 version when its released
