### ISSUE TITLE
Tinkers Construct InGameManual can be changed 

### ISSUE THREAD

**Issue by LastDawn** [LepkoQQ/EasyCrafting#19]
The manual that spawns in your Inventory can be crafted around ino to the other versions that are supposed to spawn later after other prequsites are met.

Forge Version: 7.8.0.700
EasyCrafting 1.1.5
TConstruct 1.3.3.15

**Comment by LepkoQQ** [comment]
This is not a bug. Tinkers construct provides recipes to craft its books in to other books. (probably in case you lose it or want another copy)
