### ISSUE TITLE
Issue with Ingot-to-Block-Crafting when GregTec is installed, Huge performance Issue

### ISSUE THREAD

**Issue by LastDawn** [LepkoQQ/EasyCrafting#20]
The EasyCrafing Table makes it possible to craft blocks from Ingots even if GregTec is installed. 
This recipe is disabled by default in that mod, creating block requires a compressor machine. There is also some funkyness with different Oredictionary Version of Ingots and Blocks, you are able to craft blockversion from different Ingots then your are supppsed to (Disreagarding that GregTec should make only the creation of its own block via compressor possible).

Also a huge performance Issue when right-clicking to craft blocks ( Could be caused by the crafting table trying to continously craft and uncraft blocks since righ-clicking craft as many as possible afik) that can crash clients and servers or in lesser cases lock them up for quite some time.
Crashlog: http://tny.cz/edbc26aa
More Logs: http://pastebin.com/g3NmH2DA
Some more testing showed that with recipeRecursion=2 this no longer seems to be an Issue, but on the default level of 10 it can take up to 140 seconds for the crafting to finish.

**Comment by LepkoQQ** [comment]
Hmm.. Haven't tested with GregTech much. Will take a look when I get some time.

**Comment by VoxPopuliZombiemold** [comment]
I would like to update and say that these issues are still happening. If you would like further information, please feel free to ask, as I can help setup the scenario where these issues occur.

**Comment by LepkoQQ** [comment]
for now i wont support gregtech, maybe in a future version
