### ISSUE TITLE
[1.6.4] Server Crash

### ISSUE THREAD

**Issue by Soundtoxin** [LepkoQQ/EasyCrafting#26]
http://a.pomf.se/zhqnif.txt

Here's the closest I have to a crash log. Everyone gets dc'd and the server freezes up. I have to stop it myself (by pressing control c in the terminal window)

Someone was crafting an ME Storage Bus and it was crashing

**Comment by LepkoQQ** [comment]
there is no official version for 1.6.4 by me, if you downloaded from somewhere else this is their issue
