### ISSUE TITLE
Possible Enhancement: Resources List and Description

### ISSUE THREAD

**Issue by UberWaffe** [LepkoQQ/EasyCrafting#3]
It would be awesome if like Crafting Table you could display a resources list (what will you use up to make this) when hovering over an item in the GUI.

Additionally, it would be neat if there was a third tab, where if you selected an item you could get a description of the item (defined in some custom file). External file would allow for localization of languages by users.
In game description would go a long way to help explain some more advanced items/blocks and help reduce wiki reliance.

**Comment by ogredude** [comment]
I love the idea of the resource list!  I'd love it if you could hover over an item highlighted in red (you're missing some material for it) and it'd show you exactly what resources you're missing.

**Comment by LepkoQQ** [comment]
resource list is implemented, no current plans to add information tab
