### ISSUE TITLE
Add an expensive mode

### ISSUE THREAD

**Issue by hvdklauw** [LepkoQQ/EasyCrafting#4]
I like that it makes it easier to craft things but not at the start of the game..
After I have some resources the crafting of all the little ic2 components to get something better really gets to me.. this could help me there but then it needs to be more expensive.
Add config option so you can make it very expensive (diamond block or something).

**Comment by LepkoQQ** [comment]
You can specify custom item ids for the easycrafting table in the config file now. Closing
