### ISSUE TITLE
Question: Any interest in a pull request for Code Comments?

### ISSUE THREAD

**Issue by UberWaffe** [LepkoQQ/EasyCrafting#6]
I'm busy adding comments to your code as I figure out what the code does and why.

I could submit a pull request for the comments (for you to pull in) if you want.

You can always reject the pull request if the comments are not up to standard or wrong.

**Comment by LepkoQQ** [comment]
Yeah, sure. Don't go crazy with the comments. Will definetly check and pull if you add javadoc.

**Comment by UberWaffe** [comment]
Ah, okay. Whoops.

I'll rework the comments to fit the javadoc format (checking it out now). And will strip out the surplus comments.
