### ISSUE TITLE
BUG v. 1.1.0 "Doesn't work on a server"

### ISSUE THREAD

**Issue by doblez** [LepkoQQ/EasyCrafting#9]
I've found a bug, and i don't know if its just me, but when i'am using this mod with the FTB modpack in SP, the mod works like a charm, but when i try to load the mod onto a server, it will allow me to place the block, and open it op, but i will not allow me to craft stuff. Like if i try to make 4 sand into sandstone, and i then click sandstone, it won't add sandstone to my inventory, nor will it take any 'ingredients'. If i try to hold the mouse button down, it will still vanish into the GUI again, and as before, no product for me.
I've also made a forum post concerning this issue, but i thought that i might as well put one here.

**Comment by LepkoQQ** [comment]
Should be fixed in 08b48fdb4946857bf0c24575d7ac3cebd4ceddba
